### ISSUE TITLE
Poderia ter mais detalhes no README?

### ISSUE THREAD

**Issue by skatesham** [MaxwellOlliver/uiclone-riot-client#1]
Digo ter mais detalhes no README como:
1. Como desenvolver
2. Descrições
3. Linguagens e tecnologias

**Comment by MaxwellOlliver** [comment]
Quando eu tiver um tempo livre, estarei fazendo um README melhor

**Comment by skatesham** [comment]
Engraçado que nunca temos mais tempo depois hehehe.

**Comment by MaxwellOlliver** [comment]
> Engraçado que nunca temos mais tempo depois hehehe.

então, final de curso, TCC em andamento. Tempo tá difícil kkk
